blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from rest_framework_simplejwt.authentication import JWTAuthentication
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions


schema_view = get_schema_view(
    openapi.Info(
        title="Blog API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@blog.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
    authentication_classes=(JWTAuthentication,),
)



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blogs.urls')),
    path('',include('blogs_api.urls')),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blogs/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/',views.register_page, name='register_page'),
    path('login/',views.login_page, name='login_page'),
    path('logout/', views.logout_page, name ='logout_page'),
    path('create/',views.create_blog, name='create_blog'),
    path('blogs/',views.blog_list,name='blog_list'),
    path('blog/<int:pk>',views.blog_detail,name='blog_detail'),
    path('blog/<int:pk>/delete',views.blog_delete,name='blog_delete'),
    path('blog/<int:pk>edit/',views.blog_edit,name='blog_edit'),
    path('category/<int:category_id>',views.blog_category,name='blog_category'),
    path('like/<int:pk>',views.blog_like,name='blog_like'),
    path('comment/<int:pk>/delete',views.delete_comment,name='delete_comment'),
    path('ajax/load-tags/', views.load_tags, name='ajax_load_tags'),
    path('dashboard',views.user_dashboard,name='user_dashboard'),
]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField

class Category(models.Model):
    name = models.CharField(max_length=200)
    
    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=200)
    category = models.ForeignKey(Category,on_delete=models.CASCADE,related_name='tags')
    
    def __str__(self):
        return self.name

class blog_post(models.Model):
    title = models.CharField(max_length=200)
    content = RichTextField()
    date_posted = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='images/',blank=True, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, blank=True, null= True)
    tags = models.ManyToManyField(Tag ,blank=True)
    likes = models.ManyToManyField(User,related_name='liked_posts',blank=True)
    
    def total_likes(self):
        return self.likes.count()
    def __str__(self):
        return self.title

class Comment(models.Model):
    blog = models.ForeignKey(blog_post, related_name='comments',on_delete=models.CASCADE)
    Author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    date_posted = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'Comment by {self.author} on {self.blog}'

blogs/forms.py
from django import forms
from .models import blog_post, Comment, Tag
from ckeditor.widgets import CKEditorWidget

class BlogPostForm(forms.ModelForm):
    content = forms.CharField(widget=CKEditorWidget())
    class Meta:
        model = blog_post
        fields = ['title', 'content', 'image', 'category', 'tags']
        widgets = {
            'tags': forms.SelectMultiple(attrs={'id': 'id_tags'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['tags'].queryset = Tag.objects.none()

        if 'category' in self.data:
            try:
                category_id = int(self.data.get('category'))
                self.fields['tags'].queryset = Tag.objects.filter(category_id=category_id).order_by('name')
            except (ValueError, TypeError):
                pass  
        elif self.instance.pk:
            self.fields['tags'].queryset = self.instance.category.tags.order_by('name')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['content'].widget.attrs.update({'rows': 1, 'placeholder': 'Comment'})

blogs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import BlogPostForm, CommentForm
from .models import blog_post, Category, Tag, Comment
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponseForbidden, HttpResponse, JsonResponse, Http404
from django.core.paginator  import Paginator
from django.db.models import Q


def login_page(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        if not User.objects.filter(username=username).exists():
            messages.error(request, "Invalid Username")
            return redirect('login_page')
        
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, "Login Successful")
            return redirect('blog_list')  
        else:
            messages.error(request, "Invalid Password")
            return redirect('login_page')
    
    return render(request, 'blogs/login.html')

def logout_page(request):
    logout(request)
    return redirect ('login_page')

def register_page(request):
    
    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        user = User.objects.filter(username = username)
        if user.exists():
            messages.info(request, "This username is already taken")
            return redirect('register_page')
        
        if any(char.isupper() for char in username):
            messages.error(request,"All Username letters must be lowercase")
            return redirect('register_page')
        
        if len(username)<6:
            messages.error(request, "Username must be at least 6 characters long")
            return redirect('register_page')
        
        if len(password)<6:
            messages.error(request, "Password should be at least 6 characters long")
            return redirect('register_page')
        
        
        user=User.objects.create(
            first_name = first_name,
            last_name = last_name,
            username = username,
        )
        
        
        user.set_password(password)
        user.save()
        
        messages.success(request, "Account Created Successfully")
        return redirect('register_page')
    return render(request,'blogs/register.html')


@login_required(login_url="login_page")
def create_blog(request):
    if request.method == 'POST':
        form = BlogPostForm(request.POST, request.FILES)
        if form.is_valid():
            blog = form.save(commit=False)
            blog.author = request.user
            form.save()
            form.save_m2m()
            return redirect('blog_list')
        return render(request, 'blogs/create_blog.html', {'form': form})
    
    else:
        form = BlogPostForm()
        
    categories = Category.objects.all()
    tags = Tag.objects.all()
    return render(request, 'blogs/create_blog.html', {'form': form,'categories':categories,'tags':tags})
    
    

def blog_list(request):
    blog_posts = blog_post.objects.all().order_by('date_posted')
    categories = Category.objects.all()
    tags = Tag.objects.all()

    selected_tags = request.GET.getlist('tags',[])
    query = request.GET.get('q','')
    
    if query:
        blog_posts = blog_posts.filter(
            Q(title__icontains=query) | 
            Q(content__icontains=query) |
            Q(tags__name__icontains=query) |
            Q(category__name__icontains=query)
        ).distinct()
    else:
        blog_posts = blog_post.objects.all()
    
    if selected_tags:
        blog_posts = blog_posts.filter(tags__id__in=selected_tags).distinct()

        
    paginator = Paginator(blog_posts,3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    return render(request, 'blogs/blog_list.html', {
        'blog_posts': blog_posts,
        'categories':categories,
        'query':query,
        'page_obj':page_obj,
        'tags':tags,
        'selected_tags':selected_tags,
        })

# @login_required(login_url="login_page")
def blog_detail(request, pk):
    try:
        blog = get_object_or_404(blog_post, pk=pk)
        comments = blog.comments.all()
        tags = blog.tags.all()

        if request.method == 'POST':
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.blog = blog
                comment.Author = request.user
                comment.save()
                return redirect('blog_detail', pk=pk)
        else:
            comment_form = CommentForm()

        return render(request, 'blogs/blog_detail.html', {
            'blog': blog,
            'comments': comments,
            'comment_form': comment_form,
            'tags': tags,
        })

    except Http404:
        messages.error(request, "Blog post not found.")
        return redirect('blog_list')

    except Exception as e:
        messages.error(request, f"An unexpected error occurred: {e}")
        return redirect('blog_list')

    
@login_required(login_url="login_page")
def blog_delete(request, pk):
    try:
        if request.method == 'POST':
            blog = get_object_or_404(blog_post, pk=pk)

            if blog.author != request.user:
                return HttpResponseForbidden("You are not allowed to delete this!")

            blog.delete()
            return redirect('blog_list')

        else:
            return redirect('blog_detail', pk=pk)

    except Http404:
        messages.error(request, "Blog post not found.")
        return redirect('blog_list')

    except Exception as e:
        messages.error(request, f"An error occurred while trying to delete the blog: {e}")
        return redirect('blog_detail', pk=pk)

    
@login_required(login_url="login_page")
def blog_edit(request, pk):
    blog = get_object_or_404(blog_post, pk=pk)
    if blog.author!= request.user:
        return HttpResponse("You are not allowed to edit this blog!")
    
    if request.method == 'POST':
        form = BlogPostForm(request.POST, request.FILES, instance=blog)
        if form.is_valid():
            form.save()
            return redirect('blog_detail', pk=blog.pk)
    else:
        form = BlogPostForm(instance=blog)
        
    return render(request, 'blogs/blog_edit.html', {'form': form, 'blog': blog})


# @login_required(login_url="login_page")
def blog_category(request, category_id):
    category = get_object_or_404(Category,id= category_id)
    blogs = blog_post.objects.filter(category=category)
    return render(request,'blogs/blog_category.html',{'category': category, 'blogs':blogs})

@login_required(login_url="login_page")
def blog_like(request, pk):
    blog = get_object_or_404(blog_post, pk=pk)
    if request.user in blog.likes.all():
        blog.likes.remove(request.user)
    else:
        blog.likes.add(request.user)
    return redirect('blog_detail',pk=pk)


def delete_comment(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    
    if not User.is_authenticated:
        return HttpResponse("You are not allowed to delete this comment!")
    else:
        comment.delete()
        return redirect('blog_detail',pk=comment.blog.pk)

def load_tags(request):
    category_id = request.GET.get('category')
    tags = Tag.objects.filter(category_id=category_id).values('id', 'name')
    return JsonResponse(list(tags), safe=False)

@login_required
def user_dashboard(request):
    
    user_blogs = blog_post.objects.filter(author=request.user).order_by('-date_posted')
    user_comments = Comment.objects.filter(Author=request.user)
    
    return render(request,'blogs/user_dashboard.html',{
        'user_blogs':user_blogs,
        'user_comments': user_comments
    })

blogs/templates/blogs/blog_category.html
{% extends 'blogs/base/base.html' %}

{% load static %}

{% block style_css %}
<link rel="stylesheet" href="{% static 'blogs/styles/blog_category.css' %}">
{% endblock %}

{% block body %}
{% if messages %}
            <div class="messages">
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                        <span class="close-btn" onclick="this.parentElement.style.display='none';">&times;</span>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
<h1>Blogs in Category: {{ category.name }}</h1>

{% if blogs %}
    <ul>
        {% for blog in blogs %}
            <li><a href="{% url 'blog_detail' blog.pk %}">{{ blog.title }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No blogs found in this category.</p>
{% endif %}

<a href="{% url 'blog_list' %}" class="back-button">Back to All Blogs</a>
{% endblock %}

blogs/templates/blogs/blog_detail.html
{% extends 'blogs/base/base.html' %}

{% load static %}

{% block title %}{{ blog.title }}{% endblock %}

{% block style_css %}
<link rel="stylesheet" href="{% static 'blogs/styles/blog_detail.css' %}">

{% endblock %}

{% block body %}
{% if messages %}
            <div class="messages">
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                        <span class="close-btn" onclick="this.parentElement.style.display='none';">&times;</span>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    <div class="container">
        <h1>{{ blog.title }}</h1>
        <div class="blog-detail-content">
            {% if blog.image %}
                <img src="{{ blog.image.url }}" alt="Blog Image" class="blog-image">
            {% endif %}
            <div class="blog-text">
                <p>{{ blog.content|safe }}</p>
            </div>
        </div>
            
        <p>Tags: </p>
        {% for tag in tags %}
        <p>{{ tag.name }}</p>
        {% endfor %}
        <p class="blog-author"><strong>Author:</strong> {{ blog.author.username }}</p>
        <p class="blog-date"><strong>Posted on:</strong> {{ blog.date_posted }}</p>
        <a href="{% url 'blog_list' %}" class="back-button">Back to Blog List</a>
        <a href="{% url 'blog_edit' blog.pk %}" class="edit-button">Edit Blog</a>
        <form method="post" action="{% url 'blog_delete' blog.pk %}">
            {% csrf_token %}
            <button type="submit" class="delete-button">Delete Blog</button>
        </form>
        <div class="like-button">
            <form action="{% url 'blog_like' blog.id %}" method="POST">
            {% csrf_token %}
            {% if user in blog.likes.all %}
                <button type="submit" class="like-btn">Unlike</button>
            {% else %}
                <button type="submit" class="like-btn">Like</button>
            {% endif %}
            <p>{{ blog.total_likes }} likes</p>
            </form>
        </div>

        <div class="comments-section">

            {% if user.is_authenticated %}
                <h5>Leave a Comment</h5>
                <form method="POST">
                    {% csrf_token %}
                    {{ comment_form.as_p }}
                    <button type="submit">Submit Comment</button>
                </form>
            {% else %}
                <p>You must be logged in to leave a comment.</p>
            {% endif %}
        </div>

    {% for comment in blog.comments.all %}
        <div class="comment">
            <p><strong>{{ comment.Author }}</strong>: {{ comment.content }}</p>

            {% if comment.Author == request.user or user == blog.author %}
                <form method="post" action="{% url 'delete_comment' comment.id %}" style="display:inline;">
                    {% csrf_token %}
                    <button type="submit" class="delete-button">Delete</button>
                </form>
            {% endif %}
        </div>
    {% endfor %}

</div>

{% endblock %}

blogs/templates/blogs/blog_edit.html
{% extends 'blogs/base/base.html' %}

{% load static %}

{% block style_css %} 
<link rel="stylesheet" href="{% static 'blogs/styles/blog_edit.css' %}">
{% endblock %}

{% block title %}Edit Blog{% endblock %}



{% block body %}
{% if messages %}
            <div class="messages">
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                        <span class="close-btn" onclick="this.parentElement.style.display='none';">&times;</span>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    <div class="container">
        <h1>Edit Blog: {{ blog.title }}</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="save-button">Save Changes</button>
        </form>
        <a href="{% url 'blog_detail' blog.pk %}" class="back-button">Back to Blog Details</a>
    </div>
{% endblock %}

blogs/templates/blogs/blog_list.html
{% extends 'blogs/base/base.html' %}

{% load static %}

{% block style_css %} 
<link rel="stylesheet" href="{% static 'blogs/styles/blog_list.css' %}">
{% endblock %}

{% block title %}Blog List{% endblock %}

{% block body %}
{% if messages %}
            <div class="messages">
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                        <span class="close-btn" onclick="this.parentElement.style.display='none';">&times;</span>
                    </div>
                {% endfor %}
            </div>
        {% endif %}

    <div class="container">
        <h1>BLOGIFY</h1>

<div class="search-tag-container">
    
    <form method="get" class="search-form" action="{% url 'blog_list' %}">
        <input type="text" name="q" placeholder="Search">
        <button type="submit">Search</button>
    </form>
    
    <form method="get" class="tag-form" action="{% url 'blog_list' %}">
        <div class="tag-filters">
            <label for="tags">Tags:</label>
            <select name="tags" id="tags" multiple>
                {% for tag in tags %}
                    <option value="{{ tag.id }}" {% if tag.id in selected_tags %}selected{% endif %}>{{ tag.name }}</option>
                {% endfor %}
            </select>
        </div>
        <button type="submit">Filter</button>
    </form>
</div>

        <div class="create-blog-link">
            <a href="{% url 'create_blog' %}" class="create-blog-button">Create a New Blog</a>
            <a href="{% url 'user_dashboard' %}"class="create-blog-button">My Dashboard</a>

        </div>

        <div class="categories-container">
            
            <h2>Categories</h2>
            <ul class="categories-list">
                {% for category in categories %}
                <li><a href="{% url 'blog_category' category.id %}">{{ category.name }}</a></li>
                {% endfor %}
            </ul>
        </div>

        <center>  <h2>All Blogs</h2> </center>

        {% if blog_posts %}
            <ul class="blog-list">
                
                {% for blog in page_obj.object_list %}
                    <li class="blog-item">

                        <h2 class="blog-title">{{ blog.title }}</h2>
                        <div class="blog-content-wrapper">
                            {% if blog.image %}
                                <img src="{{ blog.image.url }}" alt="Blog Image" class="blog-image">
                            {% else %}
                                <p class="no-image">No image available</p>
                            {% endif %}
                            <div class="blog-content">
                                <p>{{ blog.content|safe}}</p>
                            </div>
                        </div>
                        <p class="blog-author"><strong>Author:</strong> {{ blog.author.username }}</p>
                        <p class="blog-date"><strong>Posted on:</strong> {{ blog.date_posted }}</p>
                        <p class="blog-author">{{ blog.total_likes }} likes</p>
                        <!-- <p class="blog-author">{{ blog.total_comment }}Comments</p> -->
                        <a href="{% url 'blog_detail' blog.id %}" class="view-button">View Details</a>
                        
                    </li>
                {% endfor %}
            </ul>


            <div class="pagination">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                        <a href="?page=1">&laquo; first</a>
                        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}
                
                    {% for page in page_obj.paginator.page_range %}
                        {% if page == page_obj.number %}
                            <span class="current">{{ page }}</span>
                        {% else %}
                            <a href="?page={{ page }}">{{ page }}</a>
                        {% endif %}
                    {% endfor %}
                
                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">next</a>
                        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </span>
            </div>
            
        {% else %}
            <p>No blogs found.</p>
        {% endif %}
    </div>
{% endblock %}

blogs/templates/blogs/create_blog.html
{% extends 'blogs/base/base.html' %}
{% load static %}

{% block title %}Create Blog{% endblock %}
{% block style_css %}
<link rel="stylesheet" href="{% static 'blogs/styles/create_blog.css' %}">
{% endblock %}

{% block script %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
{% endblock %}

{% block body %}
{% if messages %}
            <div class="messages">
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                        <span class="close-btn" onclick="this.parentElement.style.display='none';">&times;</span>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
<div class="container">
    <h1>Create a New Blog Post</h1>
    <form method="post" class="blog-form" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_title">Title</label>
            {{ form.title }}
        </div>
        <div class="form-group">
            <label for="id_content" id="id_content">Content</label>
            {{ form.content|safe }}
        </div>
        <div class="form-group">
            <label for="id_category">Category</label>
            {{ form.category }}
        </div>
        <div class="form-group" id="tags-container" style="display:none;">
            <label for="id_tags">Tags</label>
            <select name="tags" id="id_tags" multiple>
            </select>
        </div>
        <div class="form-group">
            <label for="id_image">Image</label>
            {{ form.image }}
        </div>
        <button type="submit" class="submit-btn">Create Blog</button>
    </form>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $('#id_category').change(function() {
            var url = "{% url 'ajax_load_tags' %}";
            var categoryId = $(this).val();

            if (categoryId) {
                $.ajax({
                    url: url,
                    data: {
                        'category': categoryId
                    },
                    success: function(data) {
                        $("#id_tags").empty(); // Clear previous tags
                        if (data.length > 0) {
                            $("#tags-container").show(); // Show tags container
                            $.each(data, function(key, value) {
                                $("#id_tags").append('<option value="' + value.id + '">' + value.name + '</option>');
                            });
                        } else {
                            $("#tags-container").hide(); // Hide tags container if no tags are returned
                        }
                    },
                    error: function(xhr, status, error) {
                        console.error("Error fetching tags:", status, error);
                    }
                });
            } else {
                $("#id_tags").empty();
                $("#tags-container").hide(); // Hide tags container if no category is selected
            }
        });
    });
</script>


{% endblock %}

blogs/templates/blogs/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'blogs/styles/login.css' %}">
    <title>Login</title>
</head>
<body>
    <div class="login-container">
        <form method="POST">
            {% csrf_token %}
            {% if messages %}
            <div class="messages">
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                        <span class="close-btn" onclick="this.parentElement.style.display='none';">&times;</span>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
            <h2>Login</h2>
            <div class="input-group">
                <label for="username">Username</label>
                <input type="text" id="username" name="username" required>
            </div>
            <div class="input-group">
                <label for="password">Password</label>
                <input type="password" id="password" name="password" required>
            </div>
            <button type="submit">Login</button>
            <p>Dont have Account <a href="{% url 'register_page' %}">Register now</a></p>
        </form>
    </div>
</body>
</html>

blogs/templates/blogs/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'blogs/styles/register.css' %}">
    <title>Register</title>
</head>
<body>

    <div class="register-container">
        <form 
        
        method="POST">
            {% csrf_token %}
            {% if messages %}
            <div class="messages">
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                        <span class="close-btn" onclick="this.parentElement.style.display='none';">&times;</span>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
        
            <h2>Register</h2>
            <div class="input-group">
                <label for="first-name">First Name</label>
                <input type="text" id="first-name" name="first_name" required>
            </div>
            <div class="input-group">
                <label for="last-name">Last Name</label>
                <input type="text" id="last-name" name="last_name" required>
            </div>
            <div class="input-group">
                <label for="text">Username</label>
                <input type="text" id="email" name="username" required>
            </div>
            <div class="input-group">
                <label for="password">Password</label>
                <input type="password" id="password" name="password" required>
            </div>
            <button type="submit">Register</button>
            <p>Already have an account? <a href="{% url 'login_page' %}">Login Now</a></p>
        </form>
    </div>
</body>
</html>

blogs/templates/blogs/user_dashboard.html
{% extends 'blogs/base/base.html' %}

{% load static %}

{% block style_css %} 
<link rel="stylesheet" href="{% static 'blogs/styles/user_dashboard.css' %}">
{% endblock %}

{% block title %}My Blogs{% endblock %}

{% block body %}
{% if messages %}
            <div class="messages">
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                        <span class="close-btn" onclick="this.parentElement.style.display='none';">&times;</span>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
<div class="container">
    <h1>User Dashboard</h1>
    
    <h2>My Blogs</h2>
    {% if user_blogs %}
        <ul>
            {% for blog in user_blogs %}
                <li><a href="{% url 'blog_detail' blog.pk %}">{{ blog.title }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>You have not created any blogs yet.</p>
    {% endif %}

    <h2>My Comments</h2>
    {% if user_comments %}
        <ul>
            {% for comment in user_comments %}
                <li>On <a href="{% url 'blog_detail' comment.blog.pk %}">{{ comment.blog.title }}</a>: {{ comment.content }}</li>
            {% endfor %}
        </ul>
    {% else %}
        <p>You have not made any comments yet.</p>
    {% endif %}
</div>

{% endblock %}